### ISSUE TITLE
IPB(IP Board) Forum integration

### ISSUE THREAD

**Issue by ashtray13** [Frug/AJAX-Chat#185]
First of all thanks for such awesome project! :+1: 
If you have a time and possibility, could you please implement integration for IPB Forums!
Because there is almost no good chat modules for this CMS today...
And whole IPB community will be very grateful!

Or maybe there is a guide for adapting the current version to IPB?
I'm a not professional in web coding, and would be grateful for any help!

Thanks!

**Comment by qasedak** [comment]
that would be great if we can use AJAX Chat with our IP Board Forums! every IP board users need a nice and powerful Chat Script like AJAX Chat. :)

**Comment by Frug** [comment]
Over the years people have done things like this. The place to ask is the IPB community, since someone needs to create/test/maintain the integration code. If you google around, you can find things like this (from the old sourceforge site: http://sourceforge.net/p/ajax-chat/discussion/774132/thread/d11f9d8c/ )

**Comment by helper007** [comment]
That would be great indeed!

This method didn't work!( http://sourceforge.net/p/ajax-chat/discussion/774132/thread/d11f9d8c/ )
See: https://groups.google.com/forum/#!topic/ajax-chat/_9v5nyfURu0
And there is no other clues what to do on the Internet!
