### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by Yushe** [Frug/AJAX-Chat#189]
Every so often when I'm on my chat the ChatBot will say "Error: Connection status: 500" how do I fix this?

**Comment by caffeinewriter** [comment]
HTTP Error 500 usually results from a coding error. Have you made any modifications to the chat software in terms of plugins? Otherwise, perhaps it's an issue in serving the PHP page the AJAX calls are sent to, or with the server itself. To fix your specific problem, you'll probably have to drill down into server logs, if possible. 

Reference:
[HTTP 5xx Status Codes(](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#5xx_Server_Error)
